### ISSUE TITLE
Usage With Version Control

### ISSUE THREAD

**Issue by whitmorekevinj** [amloveyweb/amloveyweb.github.io#4] opened 2018-07-03 18:14 UTC
After cloning a project containing uCodeEditor, the popup for installing OmniSharp comes up constantly. Everything still seems to mostly work, despite this annoyance. 

Also, if uCodeEditor is re-imported into the cloned project, **that** breaks everything. No file is able to load in the editor window.

Version 1.0.5b on Window 10 x64 with Unity 2018.1.3f1

**Comment by amlovey** [comment] 2018-07-04 01:07
The popup for installing Omnisharp will show when there are on Omnisharp is installed on the OS. This is by design. Because C# features are powered by Omnisharp.

For second issue, reopen the uCodeEditor window or restart Unity Editor will make everything back. I think this issue is caused by scripts recompilation after reimport. I will dig into it and see what I can do and fix it if possible.

**Comment by amlovey** [comment] 2018-07-17 04:55
This should be fixed in v1.0.7 which is already submitted to Asset Store.

**Closed by amlovey** 2018-07-17 04:55 UTC
Labels: bug, uCodeEditor
